%YAML:1.0
---

input_path:
/home/ljj/work/lidar_camera_p_plane/pcd
output_path:
/home/ljj/work/lidar_camera_p_plane/pcd_filter/
x_max:
6
x_min:
-6
y_max:
6
y_min:
-6
z_max:
6
z_min:
-6
ransac_threshold:
0.01
